config/routes.rb
Rails.application.routes.draw do
  resources :cliente_vehiculos

  resources :contratos

  devise_for :usuarios
  resources :centrales

  root :to => 'inicio#index'
  get 'inicio/index'

  resources :vehiculos

  resources :clientes

end

app/models/centrale.rb
class Centrale < ActiveRecord::Base
  validates :id_central, presence: true
  validates :responsable, presence: true
end

app/controllers/centrales_controller.rb
class CentralesController < ApplicationController
  before_action :set_centrale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:show, :index]

  # GET /centrales
  # GET /centrales.json
  def index
    @centrales = Centrale.all
  end

  # GET /centrales/1
  # GET /centrales/1.json
  def show
  end

  # GET /centrales/new
  def new
    @centrale = Centrale.new
  end

  # GET /centrales/1/edit
  def edit
  end

  # POST /centrales
  # POST /centrales.json
  def create
    @centrale = Centrale.new(centrale_params)

    respond_to do |format|
      if @centrale.save
        format.html { redirect_to @centrale, notice: 'Centrale was successfully created.' }
        format.json { render :show, status: :created, location: @centrale }
      else
        format.html { render :new }
        format.json { render json: @centrale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centrales/1
  # PATCH/PUT /centrales/1.json
  def update
    respond_to do |format|
      if @centrale.update(centrale_params)
        format.html { redirect_to @centrale, notice: 'Centrale was successfully updated.' }
        format.json { render :show, status: :ok, location: @centrale }
      else
        format.html { render :edit }
        format.json { render json: @centrale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centrales/1
  # DELETE /centrales/1.json
  def destroy
    @centrale.destroy
    respond_to do |format|
      format.html { redirect_to centrales_url, notice: 'Centrale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_centrale
      @centrale = Centrale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def centrale_params
      params.require(:centrale).permit(:id_central, :responsable, :direccion, :comuna, :telefono, :correo)
    end
end

app/helpers/centrales_helper.rb
module CentralesHelper
end

app/views/centrales/_form.html.erb
<%= form_for(@centrale) do |f| %>
  <% if @centrale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@centrale.errors.count, "error") %> prohibited this centrale from being saved:</h2>

      <ul>
      <% @centrale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_central %><br>
    <%= f.text_field :id_central %>
  </div>
  <div class="field">
    <%= f.label :responsable %><br>
    <%= f.text_field :responsable %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :comuna %><br>
    <%= f.text_field :comuna %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.number_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/centrales/edit.html.erb
<h1>Editar Centrales</h1>

<%= render 'form' %>

<%= link_to 'Show', @centrale %> |
<%= link_to 'Back', centrales_path %>

app/views/centrales/index.html.erb
<h1>Lista de Centrales</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Id central</th>
      <th>Responsable</th>
      <th>Direccion</th>
      <th>Comuna</th>
      <th>Telefono</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @centrales.each do |centrale| %>
      <tr>
        <td><%= centrale.id_central %></td>
        <td><%= centrale.responsable %></td>
        <td><%= centrale.direccion %></td>
        <td><%= centrale.comuna %></td>
        <td><%= centrale.telefono %></td>
        <td><%= centrale.correo %></td>
        <td><%= link_to ' Mostrar', centrale %></td>
        <td><%= link_to ' Editar', edit_centrale_path(centrale) %></td>
        <td><%= link_to ' Eliminar', centrale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Central', new_centrale_path %>

app/views/centrales/new.html.erb
<h1>Nueva central</h1>

<%= render 'form' %>

<%= link_to 'Back', centrales_path %>

app/views/centrales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id central:</strong>
  <%= @centrale.id_central %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @centrale.responsable %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @centrale.direccion %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @centrale.comuna %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @centrale.telefono %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @centrale.correo %>
</p>

<%= link_to 'Edit', edit_centrale_path(@centrale) %> |
<%= link_to 'Back', centrales_path %>