config/routes.rb
Rails.application.routes.draw do
  resources :cliente_vehiculos

  resources :contratos

  devise_for :usuarios
  resources :centrales

  root :to => 'inicio#index'
  get 'inicio/index'

  resources :vehiculos

  resources :clientes

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
<a class="navbar-brand" href="<%=root_path%>">Home</a>
    </div>
<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%=clientes_path%>">Clientes</a></li>
        <li><a href="<%=centrales_path%>">Centrales</a></li>
        <li><a href="<%=contratos_path%>">Contratos</a></li>
        <li><a href="<%=vehiculos_path%>">Vehiculos</a></li>
        <li><a href="<%=cliente_vehiculos_path%>">Cliente Vehiculos</a></li>
        <li>
        </ul>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

              <% if usuario_signed_in? %>

              <% end %>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <% if usuario_signed_in? %>
              <li><a> <%= current_usuario.email %> </a></li>
              	<li><a href="<%= edit_usuario_registration_path(current_usuario) %>">Editar Perfil</a></li>
              	<li><a href="<%= destroy_usuario_session_path %>", data-method="delete">Cerrar Session</a></li>
              <% else %>
              	<li><a href="<%= new_usuario_session_path %>">Ingresar</a></li>
              	<li><a href="<%= new_usuario_registration_path %>">Registrarse</a></li>
              <% end %>
            </ul>
          </div></li><!-- /.navbar-collapse -->
</nav>
<style>
th{
  padding: 20px;
}
</style>
<style>
body {background-color:lightgray}
h1   {color:"59E3D7"}
font   {color:olive}
p    {color:green}
</style>
</nav>