config/routes.rb
Rails.application.routes.draw do
  resources :cliente_vehiculos

  resources :contratos

  devise_for :usuarios
  resources :centrales

  root :to => 'inicio#index'
  get 'inicio/index'

  resources :vehiculos

  resources :clientes

end

app/models/cliente_vehiculo.rb
class ClienteVehiculo < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :vehiculo
end

app/controllers/cliente_vehiculos_controller.rb
class ClienteVehiculosController < ApplicationController
  before_action :set_cliente_vehiculo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:show, :index]
  respond_to :html

  def index
    @cliente_vehiculos = ClienteVehiculo.all
    respond_with(@cliente_vehiculos)
  end

  def show
    @vehiculos = @cliente_vehiculo.vehiculo.all
  end

  def new
    @cliente_vehiculo = ClienteVehiculo.new
    respond_with(@cliente_vehiculo)
  end

  def edit
  end

  def create
    @cliente_vehiculo = ClienteVehiculo.new(cliente_vehiculo_params)
    @cliente_vehiculo.save
    respond_with(@cliente_vehiculo)
  end

  def update
    @cliente_vehiculo.update(cliente_vehiculo_params)
    respond_with(@cliente_vehiculo)
  end

  def destroy
    @cliente_vehiculo.destroy
    respond_with(@cliente_vehiculo)
  end

  private
    def set_cliente_vehiculo
      @cliente_vehiculo = ClienteVehiculo.find(params[:id])
    end

    def cliente_vehiculo_params
      params.require(:cliente_vehiculo).permit(:cliente_id, :vehiculo_id)
    end
end

app/helpers/cliente_vehiculos_helper.rb
module ClienteVehiculosHelper
end

app/views/cliente_vehiculos/_form.html.erb
<%= form_for(@cliente_vehiculo) do |f| %>
  <% if @cliente_vehiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente_vehiculo.errors.count, "error") %> prohibited this cliente_vehiculo from being saved:</h2>

      <ul>
      <% @cliente_vehiculo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cliente_id %><br>
    <%= f.text_field :cliente_id %>
  </div>
  <div class="field">
    <%= f.label :vehiculo_id %><br>
    <%= f.text_field :vehiculo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cliente_vehiculos/edit.html.erb
<h1>Editar Cliente Vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente_vehiculo %> |
<%= link_to 'Back', cliente_vehiculos_path %>

app/views/cliente_vehiculos/index.html.erb
<h1>Lista Cliente Vehiculos</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Vehiculo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cliente_vehiculos.each do |cliente_vehiculo| %>
      <tr>
        <td><%= cliente_vehiculo.cliente %></td>
        <td><%= cliente_vehiculo.vehiculo %></td>
        <td><%= link_to ' Mostrar ', cliente_vehiculo %></td>
        <td><%= link_to ' Editar ', edit_cliente_vehiculo_path(cliente_vehiculo) %></td>
        <td><%= link_to ' Eliminar ', cliente_vehiculo, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cliente vehiculo', new_cliente_vehiculo_path %>

app/views/cliente_vehiculos/new.html.erb
<h1>Nuevo Cliente Vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Back', cliente_vehiculos_path %>

app/views/cliente_vehiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @cliente_vehiculo.cliente. %>
</p>

<p>
  <strong>Vehiculo:</strong>
  <%= @cliente_vehiculo.vehiculo %>
</p>

<%= link_to 'Edit', edit_cliente_vehiculo_path(@cliente_vehiculo) %> |
<%= link_to 'Back', cliente_vehiculos_path %>